### ISSUE TITLE
Paytm aes_key and sales_wallet_id

### ISSUE THREAD

**Issue by ishwarverma39** [schnmudgal/paytm-merchant#1]
Hi Sachin,
Where can I find out the aes_key and sales_wallet_id in my merchant account?

**Comment by schnmudgal** [comment]
@ishwarverma39 - An year ago, they used to be in account-details section. But PayTM keeps on changing its merchant platform and its UI quite often. So I can't say if it's not there yet.
Also, only admins of account are able to see this information. If you are not an admin, ask you team administrator who owns/created the account.
Further, you can always ask PayTM support for your credentials.

**Comment by ishwarverma39** [comment]
@schnmudgal Thanks for your reply
